name: SkyBeeCore
version: pre-1.0.1
main: de.leonheuer.skycave.skybeecore.SkyBeeCore
author: Hakuyamu
api-version: 1.16

depend:
  - Skript
  - Vault
  - LuckPerms

commands:
#  stats:
#    description: stats command
  wiki:
    description: wiki command
  showarmor:
    permission: skybee.command.showarmor