name: SkyBeeCore
version: 1.4.0
main: de.leonheuer.skycave.skybeecore.SkyBeeCore
authors: [ Hakuyamu ]
api-version: 1.18
depend: [ Skript, Vault, LuckPerms, Multiverse-Core ]

commands:
  wiki:
    description: wiki command
  back:
    description: back command
  portals:
    permission: skybee.core.command.portals
  drohne:
    description: drohne command

permissions:
  skybee.core.bypass:
    children:
      - farmworlds
      - commands