name: SkyBeeCore
version: 1.2.0
main: de.leonheuer.skycave.skybeecore.SkyBeeCore
author: Hakuyamu
api-version: 1.18
depend: [ Skript, Vault, LuckPerms ]

commands:
  wiki:
    description: wiki command
  back:
    description: back command