name: SkyBeeCore
version: 1.0.7-SNAPSHOT
main: de.leonheuer.skycave.skybeecore.SkyBeeCore
author: Hakuyamu
api-version: 1.18
depend: [ Skript, Vault, LuckPerms ]

commands:
  wiki:
    description: wiki command
  back:
    description: back command
#  stats:
#    description: stats command
#  showarmor:
#    permission: skybee.command.showarmor