name: SkyBeeCore
version: 1.4.3
main: de.leonheuer.skycave.skybeecore.SkyBeeCore
authors: [ Hakuyamu ]
api-version: 1.19
depend: [ Vault, LuckPerms, Multiverse-Core, VoteSystem ]

commands:
  wiki:
    description: wiki command
  back:
    description: back command
  portals:
    permission: skybee.core.command.portals
  drohne:
    description: drohne command
  fly:
    description: fly command

permissions:
  skybee.core.bypass:
    children:
      - farmworlds
      - commands